class Const:
    IMAP_USER = "test4site@sibedge.com"
    IMAP_PASSWORD = "Hup28813"
    MAIN_PAGE = "https://dev.sibedge.com/"
    CLIENTS_PAGE = "https://dev.sibedge.com/clients/"
    MODELS_PAGE = "https://dev.sibedge.com/models/"
    CONTACTS_PAGE = "https://dev.sibedge.com/contacts/"
    BLOG_PAGE = "https://dev.sibedge.com/blog/"
    SERVICE_DEVELOPMENT_PAGE = "https://dev.sibedge.com/services/development/"
    SERVICE_EXTENSION_PAGE = "https://dev.sibedge.com/services/team-extension/"
    SERVICE_SQUADS_PAGE = "https://dev.sibedge.com/squads-product-development/"
    SERVICE_DEVOPS_PAGE = "https://dev.sibedge.com/devops/"
    SERVICE_QA_PAGE = "https://dev.sibedge.com/qa/"
    ABOUT_US_PAGE = "https:/dev.sibedge.com/about/"
    AGILE_ARTICLE = "https://dev.sibedge.com/article/agile-and-squad-services/"
    PITFALLS_ARTICLE = "https://dev.sibedge.com/article/major-pitfalls/"
    CTO_ARTICLE = "https://dev.sibedge.com/article/ctos-reshape-it-priorities-to-overcome-crisis-mode/"
    ANCHORFREE_CASE = "https://se.sibedge.com/cases/secure-and-private-internet-for-millions-of-users/"